# Generated by Django 5.2.7 on 2025-11-15 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_schedule_constraints'),
        ('api', '0002_document_file_size_document_google_drive_embed_url_and_more'),
    ]

    operations = [
    ]
