# Generated by Django 5.2.8 on 2025-11-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_merge_20251115_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for search and tagging', max_length=500),
        ),
        migrations.AddField(
            model_name='group',
            name='possible_topics',
            field=models.TextField(blank=True, help_text='List of possible research topics, one per line'),
        ),
    ]
