# Generated by Django 5.2.8 on 2025-11-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_group_keywords_group_possible_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='abstract',
            field=models.TextField(blank=True, help_text='Brief abstract describing the proposed research topic'),
        ),
    ]