# Generated by Django 5.2.7 on 2025-11-19 05:38

from django.db import migrations, models


def set_default_status(apps, schema_editor):
    """Set default status for any groups that might have null status"""
    Group = apps.get_model('api', 'Group')
    Group.objects.filter(status__isnull=True).update(status='PENDING')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_group_status'),
    ]

    operations = [
        # First, ensure the field is nullable temporarily
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=32, null=True),
        ),
        # Run the data migration
        migrations.RunPython(set_default_status, migrations.RunPython.noop),
        # Then make it non-nullable again
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=32),
        ),
    ]
