# Generated by Django 5.2.7 on 2025-11-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_fix_group_status_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='keywords',
            field=models.TextField(blank=True, help_text='Comma-separated keywords for the thesis', null=True),
        ),
    ]
