# Generated by Django 5.2.7 on 2025-11-20 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_group_abstract'),
        ('api', '0008_alter_thesis_status'),
    ]

    operations = [
    ]
