# Generated by Django 5.2.7 on 2025-11-20 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_merge_0005_group_abstract_0008_alter_thesis_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='possible_topics',
        ),
        migrations.AddField(
            model_name='group',
            name='proposed_topic_title',
            field=models.TextField(blank=True, help_text='Proposed topic title for the research'),
        ),
    ]
