# Generated by Django 5.2.7 on 2025-11-20 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_group_possible_topics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection if status is REJECTED'),
        ),
    ]
