# Generated by Django 5.2.7 on 2025-11-20 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_group_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='status',
            field=models.CharField(choices=[('CONCEPT_SUBMITTED', 'Concept Submitted'), ('CONCEPT_SCHEDULED', 'Concept Scheduled'), ('CONCEPT_DEFENDED', 'Concept Defended'), ('CONCEPT_APPROVED', 'Concept Approved'), ('PROPOSAL_SUBMITTED', 'Proposal Submitted'), ('PROPOSAL_SCHEDULED', 'Proposal Scheduled'), ('PROPOSAL_DEFENDED', 'Proposal Defended'), ('PROPOSAL_APPROVED', 'Proposal Approved'), ('RESEARCH_IN_PROGRESS', 'Research In Progress'), ('FINAL_SUBMITTED', 'Final Submitted'), ('FINAL_SCHEDULED', 'Final Scheduled'), ('FINAL_DEFENDED', 'Final Defended'), ('FINAL_APPROVED', 'Final Approved'), ('REVISIONS_REQUIRED', 'Revisions Required'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], default='CONCEPT_SUBMITTED', max_length=32),
        ),
    ]