# Generated by Django 5.0 on 2025-11-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_thesis_status_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='defenseschedule',
            name='type',
            field=models.CharField(choices=[('CONCEPT', 'Concept'), ('FINAL', 'Final')], default='CONCEPT', max_length=16),
        ),
    ]
