# Generated by Django 5.0 on 2025-11-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_defenseschedule_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defenseschedule',
            name='type',
            field=models.CharField(choices=[('CONCEPT', 'Concept'), ('FINAL', 'Final'), ('REVIEW', 'Review')], default='CONCEPT', max_length=16),
        ),
    ]
