# Generated by Django 5.0 on 2025-11-30 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_defenseschedule_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='defense_stage',
            field=models.CharField(choices=[('concept', 'Concept'), ('proposal', 'Proposal'), ('final', 'Final')], default='concept', max_length=20),
        ),
        migrations.AlterField(
            model_name='defenseschedule',
            name='type',
            field=models.CharField(choices=[('CONCEPT', 'Concept'), ('FINAL', 'Final'), ('PROPOSAL', 'Proposal')], default='CONCEPT', max_length=16),
        ),
    ]
