# Generated by Django 5.0 on 2025-11-30 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_group_defense_stage_alter_defenseschedule_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='defense_stage',
            field=models.CharField(choices=[('CONCEPT', 'Concept'), ('FINAL', 'Final'), ('PROPOSAL', 'Proposal')], default='CONCEPT', max_length=20),
        ),
    ]
