import api from './api'
export const createGroup = (payload:any) => api.post('groups/', payload)
export const listGroups = () => api.get('groups/')
export const addMember = (groupId:number, userId:number) => api.post(`groups/${groupId}/add_member/`, { user_id:userId })
export const removeMember = (groupId:number, userId:number) => api.post(`groups/${groupId}/remove_member/`, { user_id:userId })
export const getGroup = (id:number) => api.get(`groups/${id}/`)
export const updateGroup = (id:number, payload:any) => api.patch(`groups/${id}/`, payload)
export const assignAdviser = (groupId:number, adviserId:number) => updateGroup(groupId, { adviser: adviserId })
export const assignPanels = (groupId:number, panelIds:number[]) => updateGroup(groupId, { panels: panelIds })
export const searchUsers = (q:string) => api.get(`users/?search=${encodeURIComponent(q)}`)
